ALTER TABLE permits_raw RENAME "Assessor Book" to assessor_book;
ALTER TABLE permits_raw RENAME "Assessor Page" to assessor_page;
ALTER TABLE permits_raw RENAME "Assessor Parcel" to assessor_parcel;
ALTER TABLE permits_raw RENAME "Tract" to tract;
ALTER TABLE permits_raw RENAME "Block" to block;
ALTER TABLE permits_raw RENAME "Lot" to lot;
ALTER TABLE permits_raw RENAME "Reference # (Old Permit #)" to reference_no_old_permit_no;
ALTER TABLE permits_raw RENAME "PCIS Permit #" to pcis_permit_no;
ALTER TABLE permits_raw RENAME "Status" to status;
ALTER TABLE permits_raw RENAME "Status Date" to status_date;
ALTER TABLE permits_raw RENAME "Permit Type" to permit_type;
ALTER TABLE permits_raw RENAME "Permit Sub-Type" to permit_sub_type;
ALTER TABLE permits_raw RENAME "Permit Category" to permit_category;
ALTER TABLE permits_raw RENAME "Project Number" to project_number;
ALTER TABLE permits_raw RENAME "Event Code" to event_code;
ALTER TABLE permits_raw RENAME "Initiating Office" to initiating_office;
ALTER TABLE permits_raw RENAME "Issue Date" to issue_date;
ALTER TABLE permits_raw RENAME "Address Start" to address_start;
ALTER TABLE permits_raw RENAME "Address Fraction Start" to address_fraction_start;
ALTER TABLE permits_raw RENAME "Address End" to address_end;
ALTER TABLE permits_raw RENAME "Address Fraction End" to address_fraction_end;
ALTER TABLE permits_raw RENAME "Street Direction" to street_direction;
ALTER TABLE permits_raw RENAME "Street Name" to street_name;
ALTER TABLE permits_raw RENAME "Street Suffix" to street_suffix;
ALTER TABLE permits_raw RENAME "Suffix Direction" to suffix_direction;
ALTER TABLE permits_raw RENAME "Unit Range Start" to unit_range_start;
ALTER TABLE permits_raw RENAME "Unit Range End" to unit_range_end;
ALTER TABLE permits_raw RENAME "Zip Code" to zip_code;
ALTER TABLE permits_raw RENAME "Work Description" to work_description;
ALTER TABLE permits_raw RENAME "Valuation" to valuation;
ALTER TABLE permits_raw RENAME "Floor Area-L.A. Zoning Code Definition" to floor_area_la_zoning_code_definition;
ALTER TABLE permits_raw RENAME "# of Residential Dwelling Units" to no_of_residential_dwelling_units;
ALTER TABLE permits_raw RENAME "# of Accessory Dwelling Units" to no_of_accessory_dwelling_units;
ALTER TABLE permits_raw RENAME "# of Stories" to no_of_stories;
ALTER TABLE permits_raw RENAME "Contractor's Business Name" to contractors_business_name;
ALTER TABLE permits_raw RENAME "Contractor Address" to contractor_address;
ALTER TABLE permits_raw RENAME "Contractor City" to contractor_city;
ALTER TABLE permits_raw RENAME "Contractor State" to contractor_state;
ALTER TABLE permits_raw RENAME "License Type" to license_type;
ALTER TABLE permits_raw RENAME "License #" to license_no;
ALTER TABLE permits_raw RENAME "Principal First Name" to principal_first_name;
ALTER TABLE permits_raw RENAME "Principal Middle Name" to principal_middle_name;
ALTER TABLE permits_raw RENAME "Principal Last Name" to principal_last_name;
ALTER TABLE permits_raw RENAME "License Expiration Date" to license_expiration_date;
ALTER TABLE permits_raw RENAME "Applicant First Name" to applicant_first_name;
ALTER TABLE permits_raw RENAME "Applicant Last Name" to applicant_last_name;
ALTER TABLE permits_raw RENAME "Applicant Business Name" to applicant_business_name;
ALTER TABLE permits_raw RENAME "Applicant Address 1" to applicant_address_1;
ALTER TABLE permits_raw RENAME "Applicant Address 2" to applicant_address_2;
ALTER TABLE permits_raw RENAME "Applicant Address 3" to applicant_address_3;
ALTER TABLE permits_raw RENAME "Zone" to zone;
ALTER TABLE permits_raw RENAME "Occupancy" to occupancy;
ALTER TABLE permits_raw RENAME "Floor Area-L.A. Building Code Definition" to floor_area_la_building_code_definition;
ALTER TABLE permits_raw RENAME "Census Tract" to census_tract;
ALTER TABLE permits_raw RENAME "Council District" to council_district;
ALTER TABLE permits_raw RENAME "Latitude/Longitude" to latitude_longitude;
ALTER TABLE permits_raw RENAME "Applicant Relationship" to applicant_relationship;
ALTER TABLE permits_raw RENAME "Existing Code" to existing_code;
ALTER TABLE permits_raw RENAME "Proposed Code" to proposed_code;